
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jul 13 16:30:28 BRT 2016
//----------------------------------------------------

package cupbyexampletest;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int T_WHILE = 31;
  public static final int T_EXTENDS = 6;
  public static final int T_ELSE = 30;
  public static final int T_STATIC = 8;
  public static final int T_FPARENTESES = 35;
  public static final int T_FALSE = 33;
  public static final int T_INT = 4;
  public static final int T_ACOLCHETES = 36;
  public static final int T_FCOLCHETES = 37;
  public static final int T_RETURN = 11;
  public static final int T_NOT = 21;
  public static final int T_INTEGER = 42;
  public static final int T_DIV = 27;
  public static final int T_PRINTLN = 12;
  public static final int T_MULT = 26;
  public static final int T_VIRGULA = 40;
  public static final int EOF = 0;
  public static final int T_PONTO = 18;
  public static final int error = 1;
  public static final int T_NEW = 14;
  public static final int T_E = 28;
  public static final int T_IGUAL = 22;
  public static final int T_ADD = 24;
  public static final int T_DIFERENTE = 23;
  public static final int T_ACHAVES = 38;
  public static final int T_PUBLIC = 7;
  public static final int T_FCHAVES = 39;
  public static final int T_CLASS = 5;
  public static final int T_STRING = 3;
  public static final int T_BOOL = 2;
  public static final int T_LENGTH = 13;
  public static final int T_MAIN = 9;
  public static final int T_THIS = 15;
  public static final int T_MENOR = 19;
  public static final int T_PONTOVIRGULA = 41;
  public static final int T_TRUE = 32;
  public static final int T_APARENTESES = 34;
  public static final int T_IF = 29;
  public static final int T_NULL = 16;
  public static final int T_ATRIB = 20;
  public static final int T_SUB = 25;
  public static final int T_VOID = 10;
  public static final int T_IDENTIFICADOR = 17;
}

